import type { ListingPrivate } from "@avtolink/shared";

export const featuredListings: ListingPrivate[] = [
  {
    id: "1",
    title: "BYD Song Plus EV 2024",
    make: "BYD",
    model: "Song Plus",
    year: 2024,
    powertrainType: "EV",
    trim: "Flagship",
    batteryKwh: 87,
    rangeKm: 605,
    rangeStandard: "CLTC",
    motorPowerKw: 160,
    driveType: "FWD",
    condition: "Yangi olib kelingan",
    batteryHealthPercent: 96,
    customsStatus: "Rasmiylashtirilgan",
    bodyColor: "Oq",
    vin: "LGBEVSAMPLE001",
    priceUsd: 28900,
    mileageKm: 12000,
    region: "Toshkent",
    exactLocation: "Toshkent, Sergeli avtomobil bozori",
    latitude: 41.2579,
    longitude: 69.2198,
    yandexMapUrl: "https://yandex.com/maps/?ll=69.2198,41.2579&z=16",
    sellerPhone: "+998901234567",
    sellerTelegramUsername: "aziz_auto",
    description: "Xitoydan olib kelingan, batareya holati yaxshi, oilaviy krossover.",
    photoUrls: ["https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=900&q=80"],
    status: "ACTIVE",
    seller: {
      id: "u1",
      name: "Azizbek",
      phone: "+998901234567",
      region: "Toshkent",
      createdAt: new Date().toISOString()
    },
    createdAt: new Date().toISOString()
  },
  {
    id: "2",
    title: "Li Auto L7 Pro REEV 2023",
    make: "Li Auto",
    model: "L7",
    year: 2023,
    powertrainType: "REEV",
    trim: "Pro",
    batteryKwh: 42,
    rangeKm: 1315,
    rangeStandard: "CLTC",
    motorPowerKw: 330,
    driveType: "AWD",
    condition: "A'lo",
    batteryHealthPercent: 94,
    customsStatus: "Rasmiylashtirilgan",
    bodyColor: "Kulrang",
    vin: "LIXIANGSAMPLE002",
    priceUsd: 41800,
    mileageKm: 26000,
    region: "Samarqand",
    exactLocation: "Samarqand, Rudakiy ko'chasi",
    latitude: 39.6542,
    longitude: 66.9597,
    yandexMapUrl: "https://yandex.com/maps/?ll=66.9597,39.6542&z=16",
    sellerPhone: "+998935551122",
    sellerTelegramUsername: "dilshod_ev",
    description: "REEV, 5 o'rinli premium SUV, oilaga qulay, salon toza.",
    photoUrls: ["https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=900&q=80"],
    status: "ACTIVE",
    seller: {
      id: "u2",
      name: "Dilshod",
      phone: "+998935551122",
      region: "Samarqand",
      createdAt: new Date().toISOString()
    },
    createdAt: new Date().toISOString()
  },
  {
    id: "3",
    title: "Zeekr 001 WE 2022",
    make: "Zeekr",
    model: "001",
    year: 2022,
    powertrainType: "EV",
    trim: "WE 100 kWh",
    batteryKwh: 100,
    rangeKm: 732,
    rangeStandard: "CLTC",
    motorPowerKw: 200,
    driveType: "RWD",
    condition: "Yaxshi",
    batteryHealthPercent: 91,
    customsStatus: "Rasmiylashtirilgan",
    bodyColor: "Qora",
    vin: "ZEEKRSAMPLE003",
    priceUsd: 36500,
    mileageKm: 39000,
    region: "Fargona",
    exactLocation: "Fargona, markaz",
    latitude: 40.3894,
    longitude: 71.7864,
    yandexMapUrl: "https://yandex.com/maps/?ll=71.7864,40.3894&z=16",
    sellerPhone: "+998977771010",
    sellerTelegramUsername: "malika_cars",
    description: "Katta batareya, yurish masofasi yaxshi, sportback kuzov.",
    photoUrls: ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=80"],
    status: "ACTIVE",
    seller: {
      id: "u3",
      name: "Malika",
      phone: "+998977771010",
      region: "Fargona",
      createdAt: new Date().toISOString()
    },
    createdAt: new Date().toISOString()
  }
];
